config/routes.rb
Rails.application.routes.draw do
	get '/', to: 'welcome#index', as: 'index'
	get 'profil/:id', to:'profil#perso', as: 'profil'
  get 'welcome/:id', to:'welcome#show', as: 'welcome'
  get 'static_pages/team'
  get 'static_pages/contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_many :gossips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/profil_controller.rb
class ProfilController < ApplicationController
  def perso
  	@gossips = Gossip.all
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def team
  end

  def contact
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  	@gossips = Gossip.all
  end

  def show
  	@gossips = Gossip.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profil_helper.rb
module ProfilHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>TGP</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" <%= link_to "The gossip project", index_path %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse " id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" <%= link_to "Home", index_path %> <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Team", static_pages_team_path %> </a>
      </li>
      <li class="nav-item">
        <a class="nav-link"  <%= link_to "Contact", static_pages_contact_path %></a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
</header>
<%= yield %>
  </body>
</html>

app/views/profil/perso.html.erb
<h1>Profil de <%= @gossips[((params[:id]).to_i - 1)].user.first_name %> </h1>

<div class= container>
	<p>Prénom : <%= @gossips[((params[:id]).to_i - 1)].user.first_name %></p>
	<p>Nom : <%= @gossips[((params[:id]).to_i - 1)].user.last_name %></p>

<p></p>
</div>

app/views/static_pages/contact.html.erb
<h1>Pour nous contacter:</h1>
<p>Find me in app/views/home/contact.html.erb</p>

app/views/static_pages/team.html.erb
<h1>StaticPages#team</h1>
<p>Find me in app/views/static_pages/team.html.erb</p>

app/views/welcome/index.html.erb
<h1>Bienvenue sur The Gossip Project!</h1>
<div class="container"><br />
<h3>Voici les gossips:</h3>
	
	
	<% n = 1 %>
	<p><% @gossips.each do |gossip|%>
	<% @id = n %>

<div class="card text-center">
  <div class="card-header">
  </div>
  <div class="card-body">

    <h5 class="card-title"><a <%= link_to "Gossip n°#{n}", welcome_path(@id) %> </a></h5>
    <p class="card-text"><a <%= link_to "De #{gossip.user.first_name}: 
    #{gossip[:title]}", welcome_path(@id) %> </a></p>

  </div>
  <div class="card-footer text-muted">
    2 days ago
  </div>
</div>
</div>


	<% n = n + 1 %>

    <% end %> </p>

app/views/welcome/show.html.erb
<h1><%= @gossips[((params[:id]).to_i - 1)].title %> !</h1>

<div class= "container">
	
<p> Auteur : <a <%= link_to "#{@gossips[((params[:id]).to_i - 1)].user.first_name}", profil_path(params[:id]) %> </a></p>
<h3> <%= @gossips[((params[:id]).to_i - 1)].content %> </h3>
</div>